#pragma once

#include <cstdint>

#include "ids.hpp"
#include "numeric_types.hpp"
#include "symbol.hpp"

namespace mercury::core
{

//------------------------------------------------------------------------------
// Represents a successfully executed trade.
//
// Every fill generated by the matching engine produces exactly one Trade
// object. Trades are immutable once published and may later be consumed by
// the logger, replay engine, analytics pipeline, or external market data
// interfaces.
//------------------------------------------------------------------------------
struct Trade
{
    TradeId trade_id{};

    OrderId buyer{};

    OrderId seller{};

    Symbol symbol{};

    Price price{0};

    Quantity quantity{0};

    std::uint64_t timestamp_ns{0};
};

} // namespace mercury::core